name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78ec080f61de029f606e0adcae712e283e5dfd082ce3ca089db7054378717811"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
