name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d295d7ab6244de31f36b8269015f71d1efe70023149d0c9b0049b66d9a23437"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
