name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39a204333e5ce5ea9f6d83722a6b81c2614ba6f7998f8475e4449a3266884bca"

[versions]
forge = "45.0.43"
minecraft = "1.19.4"
