name = "ISM Modpack"
author = "Seintive"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b5e6cf8159d208c0f87023d2eb3327622310c312307c50efad6aea3a0aff01b"

[versions]
forge = "45.0.64"
minecraft = "1.19.4"
