name = "ISM Modpack"
author = "Seintive"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36e937cdfab93281455edf46d5f859f413541bf0b189e6a10ca788cbcd80dac1"

[versions]
forge = "45.0.64"
minecraft = "1.19.4"
