name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90dfb4d850bd008556a8104b5aca884faa9fdae5d3abbc027e663106bda0b986"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
