name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dbd9100ec2894cac1b196cfff275fa0dce6ed28daebd1c448d93b476de35d4c"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
