name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3db7280daf47b66989f17bef94f91db3195a2768a9dc36f7d5e9faa088fc7735"

[versions]
forge = "45.0.43"
minecraft = "1.19.4"
