name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e474eadadfeb16bcef64951bae91c00c6e56f08d5204b217832ee2c668fccc1"

[versions]
forge = "45.0.64"
minecraft = "1.19.4"
