name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63b2756d83867d4b6cd90806abf3caa5b9408de02cd4df6de7ec574d3f902439"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"
