name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef1dfee7ef57a8cc1650b51ed76902020b57e4f389e1b2dd0f2affb03e233c7a"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
