name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2221cda87473d45efcf3d0ff35b493aba6654564e5b53ebb0ab3afdc5c7afea2"

[versions]
forge = "45.0.43"
minecraft = "1.19.4"
