name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "464a0353898a51c06518ff0400ad815b632b5faf0257ee6cae7de87d2b498c2a"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
