name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c442c7bdf571ecf8aa879a2b8578e539bc6f9a6a92eb2fb25eb5f976384665a"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"
