name = "ISM Modpack"
author = "Seintive"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c6b0a464d6dce5c9fc674af0f89f90469bb2b8ca9f047b2682f0c68a63d7781"

[versions]
forge = "45.0.64"
minecraft = "1.19.4"
