name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a555e348c228416cfe297595ef811aaaab0f04941821a7e58247202eef0a0c1c"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
