name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d47b5b7e97a75ef43ba85e922a78ebc0e05487ffd504da6a25919121f13aed27"

[versions]
forge = "45.0.43"
minecraft = "1.19.4"
