name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01d5c69204e7a787fc95e124530d2add84e74caab50bebe34b063e133bb69eff"

[versions]
forge = "45.0.43"
minecraft = "1.19.4"
