name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ca141911e180c426b4f33dd221f7310853edac468709c5cf66bfa690bcb29bb"

[versions]
forge = "45.0.43"
minecraft = "1.19.4"
