name = "ISM Modpack"
author = "Seintive"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcd884c954aefc1d08c3a9f22582410334b1d150a18c4256bc89f2f8e839f102"

[versions]
forge = "45.1.0"
minecraft = "1.19.4"
