name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acc099f326370864653fa5dd3ceba3e1087a24d14dc18cb82494d6a79a0d44f1"

[versions]
forge = "45.0.43"
minecraft = "1.19.4"
