name = "ISM Modpack"
author = "Seintive"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecaa65a03a13be71b2b3c579dd5aa4779843322a201d37030f7ac59b10d27935"

[versions]
forge = "45.0.64"
minecraft = "1.19.4"
