name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7fa4159a15c105c33ed705c44b0d6793847027f79e8908a1ae5d48db6226c91"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
