name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bedbf7a3fac79c48ec4bc69fe7525ada4b900018a9fe74dc4a2bd8101429147"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"
