name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c88ff627a34c58ceb8e581fd03f278503ccd9ce20040b25f8350acec9fb9ba8d"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"
