name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ec8d4d40ddac98798612a2ab7c7e124f6ea553daa6e383082a1120d1e6b855a"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"
