name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b7154b38c8f467a40ddf3a03d61bdf33f054f6c1aacc5aa621a39b1785ec0d7"

[versions]
forge = "45.0.64"
minecraft = "1.19.4"
