name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "260b0361f3ebe36b92a566bf891f3551c70fb60ffa30ed6552d54c52ddee1eab"

[versions]
forge = "45.0.64"
minecraft = "1.19.4"
