name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "667860fa3aa3ff722409724f2c2e5af7d229fe153a30ca24ba0c92f80f42fe9f"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
