name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00a86efac8dd64bb0171ae6860e369303664166af559dd654703feee03165cbe"

[versions]
forge = "45.0.43"
minecraft = "1.19.4"
