name = "ISM Modpack"
author = "Seintive"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68388fb6458ba799f0b5dd0c1085add011a88644982d7236dec2743b592bab44"

[versions]
forge = "45.0.64"
minecraft = "1.19.4"
