name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3e5f3f3eb7f7f4fe4b2e1e219e3c4f313b5e060cc96cac4f495475190279aac"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
