name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe98ab29094de420ce84b920f0746ec2fcc953ccd71f66418f5dac509bdce30c"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
