name = "ISM Modpack"
author = "Seintive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c6beb05df79c4ff0371a85809e9fd12e38aefa4ccdfaf30b7fe26bb3efd31c0"

[versions]
forge = "45.0.59"
minecraft = "1.19.4"
